2022-08-07 13:01:47 - get_log.py - [line:133] - INFO - [日志信息]: 开始执行用例
2022-08-07 13:02:46 - get_log.py - [line:133] - INFO - [日志信息]: 用户登录
2022-08-07 13:02:55 - get_log.py - [line:133] - INFO - [日志信息]: 设备状态是icon icon--online
2022-08-07 13:03:00 - get_log.py - [line:133] - INFO - [日志信息]: 选择指定设备成功
2022-08-07 13:03:03 - get_log.py - [line:133] - INFO - [日志信息]: 这是第1次进入
2022-08-07 13:03:07 - get_log.py - [line:133] - INFO - [日志信息]: 这是第2次进入
2022-08-07 13:03:12 - get_log.py - [line:133] - INFO - [日志信息]: 这是第3次进入
2022-08-07 13:03:16 - get_log.py - [line:140] - ERROR - [日志信息]: 进入远程管理页面失败
2022-08-07 13:03:16 - get_log.py - [line:133] - INFO - [日志信息]: 这是第1次进入
2022-08-07 13:03:21 - get_log.py - [line:133] - INFO - [日志信息]: 这是第2次进入
2022-08-07 13:03:25 - get_log.py - [line:133] - INFO - [日志信息]: 这是第3次进入
2022-08-07 13:03:29 - get_log.py - [line:140] - ERROR - [日志信息]: 进入远程管理页面失败
2022-08-07 13:03:29 - get_log.py - [line:133] - INFO - [日志信息]: 用例执行结束
